"""
Plan Ranker
============
Scores and ranks execution plans generated by the LLM. Each plan gets a
composite confidence score and risk assessment that determines:

1. How confident we are the plan addresses the actual threat
2. How risky the plan is to execute (false positive impact)
3. What automation tier applies (how much human involvement needed)

Confidence formula:
    confidence = (model_confidence × 0.4) + (cve_match_score × 0.3) + (asset_criticality_score × 0.3)

Risk assessment factors:
    - Action destructiveness (isolate_host > firewall_block > notify)
    - Action reversibility (irreversible actions are riskier)
    - False positive probability (1 - anomaly_score)
"""

import logging
import uuid
from typing import Optional

from agentic.orchestrator.config import OrchestratorConfig

logger = logging.getLogger(__name__)

# Action destructiveness weights (higher = more disruptive)
ACTION_DESTRUCTIVENESS = {
    "isolate_host": 0.9,
    "credential_rotate": 0.8,
    "firewall_block": 0.6,
    "rate_limit": 0.4,
    "patch": 0.5,
    "deep_inspect": 0.1,
    "notify": 0.05,
    "firewall_unblock": 0.2,
    "restore_host": 0.3,
}


def rank_plans(raw_plans: list[dict], state: dict) -> list[dict]:
    """
    Score, enrich, and rank plans based on context from the orchestrator state.

    Args:
        raw_plans: Plans from the LLM (may lack confidence/risk fields)
        state: Current OrchestratorState with CVE, asset, and triage context

    Returns:
        List of plans sorted by confidence descending, each enriched with
        computed confidence, risk_level, and automation_tier.
    """
    anomaly_score = state.get("anomaly_score", 0.5)
    max_cvss = state.get("max_cvss", 0.0)
    max_asset_crit = state.get("max_asset_criticality", 5)
    has_exploit = state.get("has_active_exploit", False)
    cve_matches = state.get("cve_matches", [])

    # Compute CVE match score (best match confidence or 0 if none)
    cve_match_score = 0.0
    if cve_matches:
        cve_match_score = max(
            c.get("match_confidence", 0) for c in cve_matches
        )

    # Asset criticality score (inverted: tier 1 = 1.0, tier 5 = 0.2)
    asset_crit_score = (6 - max_asset_crit) / 5.0

    ranked = []
    for plan in raw_plans:
        enriched = _score_plan(plan, anomaly_score, cve_match_score,
                               asset_crit_score, has_exploit)
        ranked.append(enriched)

    # Sort by confidence descending
    ranked.sort(key=lambda p: p.get("confidence", 0), reverse=True)

    logger.info(
        f"Ranked {len(ranked)} plans. "
        f"Best: confidence={ranked[0].get('confidence', 0):.2f}" if ranked else "No plans"
    )

    return ranked


def _score_plan(
    plan: dict,
    anomaly_score: float,
    cve_match_score: float,
    asset_crit_score: float,
    has_exploit: bool,
) -> dict:
    """Score a single plan and enrich it with computed fields."""
    # Get model's self-reported confidence (may be absent or unreliable)
    model_confidence = plan.get("confidence", 0.5)

    # Composite confidence
    confidence = (
        (model_confidence * 0.4) +
        (cve_match_score * 0.3) +
        (asset_crit_score * 0.3)
    )

    # Exploit bonus: if we know there's an active exploit, boost confidence
    if has_exploit and confidence < 0.9:
        confidence = min(confidence + 0.1, 0.95)

    # Calculate plan risk (based on action destructiveness and reversibility)
    actions = plan.get("actions", [])
    if actions:
        max_destructiveness = max(
            ACTION_DESTRUCTIVENESS.get(a.get("type", ""), 0.5)
            for a in actions
        )
        irreversible_count = sum(1 for a in actions if not a.get("reversible", True))
        reversibility_penalty = irreversible_count * 0.1

        # Risk = destructiveness weighted by false positive chance
        false_positive_chance = 1 - anomaly_score
        plan_risk = max_destructiveness * (0.5 + false_positive_chance * 0.5)
        plan_risk += reversibility_penalty
        plan_risk = min(plan_risk, 1.0)
    else:
        plan_risk = 0.5

    # Map risk to level
    if plan_risk >= 0.8:
        risk_level = "critical"
    elif plan_risk >= 0.5:
        risk_level = "high"
    elif plan_risk >= 0.25:
        risk_level = "medium"
    else:
        risk_level = "low"

    # Determine automation tier
    automation_tier = OrchestratorConfig.get_automation_tier(confidence)

    # Ensure all actions have IDs
    for action in actions:
        if "action_id" not in action:
            action["action_id"] = f"act-{uuid.uuid4().hex[:8]}"

    # Ensure plan has an ID
    if "plan_id" not in plan:
        plan["plan_id"] = f"plan-{uuid.uuid4().hex[:8]}"

    # Compute total duration
    total_duration = sum(a.get("estimated_duration_seconds", 60) for a in actions)

    # Return enriched plan
    plan.update({
        "confidence": round(confidence, 3),
        "risk_level": risk_level,
        "automation_tier": automation_tier,
        "estimated_total_duration": total_duration,
    })

    return plan
