"""
Pydantic models for the simplified agentic layer.
"""
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime


class AlertData(BaseModel):
    """Incoming alert from detection service."""
    alert_id: str
    timestamp: str
    anomaly_score: float
    classification: str
    feature_vector: Dict[str, Any]
    model_votes: List[Dict[str, Any]]


class AssetContext(BaseModel):
    """Results from asset discovery agent."""
    dst_reachable: Optional[bool] = None
    dst_hostname: Optional[str] = None
    dst_ownership: Optional[str] = None
    open_ports: Optional[List[int]] = None
    local_asset: Optional[Dict[str, Any]] = None
    source_assessment: Optional[str] = None


class CVEMatch(BaseModel):
    """CVE match from lookup agent."""
    cve_id: str
    cvss_score: Optional[float] = None
    severity: Optional[str] = None
    description: Optional[str] = None
    affected_product: Optional[str] = None
    affected_versions: Optional[str] = None
    exploit_available: bool = False


class Action(BaseModel):
    """Single remediation action."""
    action_id: str
    type: str = Field(..., description="notify, investigate, block_ip")
    target: str
    params: Dict[str, Any] = {}
    rationale: str
    reversible: bool = True
    estimated_duration_seconds: int = 60


class Plan(BaseModel):
    """Remediation plan generated by LLM."""
    plan_id: str
    confidence: float = Field(..., ge=0, le=1)
    risk_level: str = Field(..., description="low, medium, high")
    aggression: str = Field(..., description="conservative, moderate, aggressive")
    threat_summary: str
    actions: List[Action]


class OrchestratorState(BaseModel):
    """State for LangGraph workflow."""
    alert_id: str
    alert_raw: Dict[str, Any]
    classification: str
    src_ip: str
    dst_ip: str
    dst_port: int
    anomaly_score: float
    
    # Agent results
    asset_context: Optional[AssetContext] = None
    cve_matches: List[CVEMatch] = []
    
    # LLM results
    plans: List[Plan] = []
    
    # Status
    status: str = "received"
    error: Optional[str] = None
