#!/usr/bin/env python3
"""Generate streaming test data for Sentinel SOC dashboard.

Simulates real-time alerts, traces, and plans being generated by the system.
Can run once or continuously to stream data.
"""

import asyncio
import json
import random
import sys
import os
from datetime import datetime, timedelta

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from db.connection import init_pool, close_pool, get_pool
from core.security import hash_password
from ws.manager import manager

# Alert scenarios for realistic data generation
ALERT_SCENARIOS = [
    {
        "classification": "SQL Injection Attempt",
        "priority": "critical",
        "src_ip": "203.0.113.{}",
        "dst_port": 5432,
        "anomaly_score_range": (0.85, 0.98),
    },
    {
        "classification": "Brute Force SSH",
        "priority": "high",
        "src_ip": "198.51.100.{}",
        "dst_port": 22,
        "anomaly_score_range": (0.70, 0.90),
    },
    {
        "classification": "Port Scan Detected",
        "priority": "medium",
        "src_ip": "192.0.2.{}",
        "dst_port": random.choice([80, 443, 8080, 22, 3389]),
        "anomaly_score_range": (0.60, 0.80),
    },
    {
        "classification": "Malware Beacon Detected",
        "priority": "critical",
        "src_ip": "185.220.101.{}",
        "dst_port": 443,
        "anomaly_score_range": (0.90, 0.99),
    },
    {
        "classification": "Privilege Escalation Attempt",
        "priority": "high",
        "src_ip": "10.0.1.{}",
        "dst_port": 445,
        "anomaly_score_range": (0.75, 0.92),
    },
    {
        "classification": "Data Exfiltration Detected",
        "priority": "critical",
        "src_ip": "10.0.2.{}",
        "dst_port": random.choice([443, 53, 123]),
        "anomaly_score_range": (0.88, 0.98),
    },
    {
        "classification": "Ransomware Activity",
        "priority": "critical",
        "src_ip": "10.0.3.{}",
        "dst_port": 445,
        "anomaly_score_range": (0.92, 0.99),
    },
    {
        "classification": "Suspicious PowerShell",
        "priority": "high",
        "src_ip": "10.0.4.{}",
        "dst_port": 5985,
        "anomaly_score_range": (0.65, 0.85),
    },
    {
        "classification": "DDoS Attack",
        "priority": "medium",
        "src_ip": "185.220.{}.100",
        "dst_port": 80,
        "anomaly_score_range": (0.55, 0.75),
    },
    {
        "classification": "Credential Stuffing",
        "priority": "high",
        "src_ip": "198.51.100.{}",
        "dst_port": 443,
        "anomaly_score_range": (0.70, 0.88),
    },
]

# Reasoning trace templates
TRACE_TEMPLATES = [
    {"agent_name": "orchestrator", "action": "alert_received", "rationale_template": "Alert ingested from {}"},
    {"agent_name": "cve_lookup", "action": "cve_search", "rationale_template": "Searching CVE database for {} signatures"},
    {"agent_name": "asset_discovery", "action": "asset_resolve", "rationale_template": "Resolved {} to asset inventory"},
    {"agent_name": "threat_intel", "action": "intel_lookup", "rationale_template": "Querying threat intel for IP {}"},
    {"agent_name": "behavioral_analysis", "action": "pattern_match", "rationale_template": "Matching behavioral patterns for {}"},
    {"agent_name": "planning", "action": "plan_generation", "rationale_template": "Generating remediation plans for {}"},
    {"agent_name": "risk_engine", "action": "risk_assessment", "rationale_template": "Calculating risk score for {}"},
]

# Plan action templates
ACTION_TEMPLATES = {
    "automated": [
        {"action_type": "notify", "rationale": "Notify SOC team of suspicious activity"},
        {"action_type": "deep_inspect", "rationale": "Capture detailed logs for analysis"},
    ],
    "semi_automated": [
        {"action_type": "firewall_block", "rationale": "Block suspicious source IP"},
        {"action_type": "rate_limit", "rationale": "Apply rate limiting to prevent abuse"},
    ],
    "manual": [
        {"action_type": "isolate_host", "rationale": "Isolate potentially compromised host"},
        {"action_type": "credential_rotate", "rationale": "Rotate credentials for affected accounts"},
        {"action_type": "patch", "rationale": "Apply security patches"},
    ],
}


def generate_alert_id():
    """Generate unique alert ID."""
    import uuid
    return f"{uuid.uuid4().hex[:8]}-{random.randint(1000, 9999)}"


def generate_ip(template):
    """Generate IP from template with random octet."""
    if "{}" in template:
        return template.format(random.randint(1, 254))
    return template


def generate_plans(alert_type, priority):
    """Generate execution plans for an alert."""
    plans = []
    
    # Determine number of plans based on priority
    num_plans = {"critical": 3, "high": 2, "medium": 2, "low": 1}.get(priority, 1)
    
    tiers = ["automated", "semi_automated", "manual"]
    
    for i in range(num_plans):
        tier = tiers[min(i, len(tiers) - 1)]
        actions = []
        
        # Add actions based on tier
        if tier == "automated":
            actions.extend(ACTION_TEMPLATES["automated"])
        elif tier == "semi_automated":
            actions.extend(ACTION_TEMPLATES["automated"][:1])
            actions.extend(ACTION_TEMPLATES["semi_automated"][:1])
        else:
            actions.extend(ACTION_TEMPLATES["manual"][:2])
        
        # Add target IPs
        for action in actions:
            if action["action_type"] in ["firewall_block", "isolate_host"]:
                action["target"] = generate_ip("203.0.113.{}")
            elif action["action_type"] == "notify":
                action["target"] = "soc-team"
            else:
                action["target"] = generate_ip("10.0.1.{}")
            action["parameters"] = {}
        
        plan = {
            "plan_id": f"plan-{random.randint(1000, 9999)}",
            "automation_tier": tier,
            "risk_level": priority if priority != "low" else "medium",
            "confidence": round(random.uniform(0.75, 0.98), 2),
            "rationale": f"Recommended {tier} response for {alert_type}",
            "actions": actions,
        }
        plans.append(plan)
    
    return {"plans": plans}


def generate_traces(alert_id, scenario, num_traces=5):
    """Generate reasoning traces for an alert."""
    traces = []
    base_time = datetime.now() - timedelta(minutes=random.randint(1, 30))
    
    for i in range(num_traces):
        template = random.choice(TRACE_TEMPLATES)
        trace = {
            "event_id": f"ev-{alert_id[:4]}-{i:03d}",
            "alert_id": alert_id,
            "event_type": template["action"],
            "agent_name": template["agent_name"],
            "action": template["action"],
            "rationale": template["rationale_template"].format(scenario["classification"]),
            "confidence": round(random.uniform(0.60, 0.95), 2) if random.random() > 0.3 else None,
            "duration_ms": random.randint(10, 1500),
            "timestamp": base_time + timedelta(seconds=i * 30),  # Return datetime object
        }
        traces.append(trace)
    
    return traces


async def generate_single_alert(pool, broadcast=True):
    """Generate one alert with plans and traces."""
    async with pool.acquire() as conn:
        # Select random scenario
        scenario = random.choice(ALERT_SCENARIOS)
        alert_id = generate_alert_id()
        
        # Generate data
        plans = generate_plans(scenario["classification"], scenario["priority"])
        traces = generate_traces(alert_id, scenario)
        
        # Insert incident
        src_ip = generate_ip(scenario["src_ip"])
        dst_ip = generate_ip("10.0.1.{}")
        anomaly_score = round(random.uniform(*scenario["anomaly_score_range"]), 3)
        
        await conn.execute(
            """INSERT INTO incidents 
               (alert_id, classification, priority, approval_status, execution_status,
                src_ip, dst_ip, dst_port, anomaly_score, plans_generated, created_at)
               VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())""",
            alert_id,
            scenario["classification"],
            scenario["priority"],
            "received",
            "pending",
            src_ip,
            dst_ip,
            scenario["dst_port"],
            anomaly_score,
            json.dumps(plans)
        )
        
        # Insert traces
        for trace in traces:
            await conn.execute(
                """INSERT INTO reasoning_traces 
                   (event_id, alert_id, event_type, agent_name, action, rationale,
                    confidence, duration_ms, timestamp)
                   VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)""",
                trace["event_id"],
                trace["alert_id"],
                trace["event_type"],
                trace["agent_name"],
                trace["action"],
                trace["rationale"],
                trace["confidence"],
                trace["duration_ms"],
                trace["timestamp"]
            )
        
        # Broadcast via WebSocket if enabled
        if broadcast:
            await manager.broadcast("feed", {
                "type": "new_alert",
                "alert_id": alert_id,
                "classification": scenario["classification"],
                "priority": scenario["priority"],
                "anomaly_score": anomaly_score,
                "src_ip": src_ip,
                "created_at": datetime.now().isoformat(),
                "has_plans": True
            })
        
        print(f"Generated: {alert_id} - {scenario['classification']} ({scenario['priority']})")
        return alert_id


async def generate_batch(count=5, delay_seconds=2):
    """Generate multiple alerts with streaming effect."""
    await init_pool()
    pool = await get_pool()
    
    print(f"Generating {count} streaming alerts...")
    generated = []
    
    for i in range(count):
        alert_id = await generate_single_alert(pool, broadcast=True)
        generated.append(alert_id)
        
        if i < count - 1:  # Don't delay after the last one
            await asyncio.sleep(delay_seconds)
    
    await close_pool()
    print(f"\nGenerated {len(generated)} alerts:")
    for aid in generated:
        print(f"  - {aid}")


async def continuous_stream(interval_seconds=30):
    """Continuously generate alerts for live demo."""
    await init_pool()
    pool = await get_pool()
    
    print(f"Starting continuous stream (interval: {interval_seconds}s)")
    print("Press Ctrl+C to stop\n")
    
    count = 0
    try:
        while True:
            alert_id = await generate_single_alert(pool, broadcast=True)
            count += 1
            print(f"  [Total: {count}] Next alert in {interval_seconds}s...\n")
            await asyncio.sleep(interval_seconds)
    except KeyboardInterrupt:
        print(f"\n\nStopped. Generated {count} alerts total.")
    finally:
        await close_pool()


async def main():
    """Main entry point with CLI args."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Generate streaming test data")
    parser.add_argument("--count", "-n", type=int, default=5, help="Number of alerts to generate")
    parser.add_argument("--delay", "-d", type=float, default=2, help="Delay between alerts (seconds)")
    parser.add_argument("--continuous", "-c", action="store_true", help="Continuous streaming mode")
    parser.add_argument("--interval", "-i", type=int, default=30, help="Interval for continuous mode")
    
    args = parser.parse_args()
    
    if args.continuous:
        await continuous_stream(args.interval)
    else:
        await generate_batch(args.count, args.delay)


if __name__ == "__main__":
    asyncio.run(main())
