"""
Execution Plan Models
======================
Models for the plans generated by the Planning Agent (LLM) and the approval
and execution lifecycle. Each alert produces a PlanSet containing 2-3
ranked plans with different aggression levels.

Lifecycle:
    PlanSet (generated) → ApprovedAction (analyst picks) → ActionResult (executed)
"""

from datetime import datetime
from typing import Optional, Literal
from pydantic import BaseModel, Field
import uuid


class Action(BaseModel):
    """A single executable action within a plan."""
    action_id: str = Field(
        default_factory=lambda: f"act-{uuid.uuid4().hex[:8]}",
        description="Unique action identifier"
    )
    type: Literal[
        "firewall_block", "firewall_unblock",
        "isolate_host", "restore_host",
        "patch", "notify", "deep_inspect",
        "rate_limit", "credential_rotate"
    ] = Field(..., description="Action type determining which executor handles it")
    target: str = Field(..., description="Target of the action (IP, hostname, or team name)")
    params: dict = Field(default_factory=dict, description="Action-specific parameters")
    rationale: str = Field(..., description="Why this action is recommended")
    reversible: bool = Field(True, description="Whether this action can be rolled back")
    estimated_duration_seconds: int = Field(60, description="Expected execution time")


class ExecutionPlan(BaseModel):
    """
    A single execution plan: a coherent set of actions to address a threat.
    The Planning Agent generates multiple plans with different aggression levels.
    """
    plan_id: str = Field(
        default_factory=lambda: f"plan-{uuid.uuid4().hex[:8]}",
        description="Unique plan identifier"
    )
    alert_id: str = Field(..., description="Alert this plan addresses")
    confidence: float = Field(
        ..., ge=0.0, le=1.0,
        description="Overall confidence score for this plan"
    )
    risk_level: Literal["low", "medium", "high", "critical"] = Field(
        ..., description="Risk of executing this plan (accounts for false positive chance)"
    )
    automation_tier: Literal[
        "auto_execute", "auto_recommend", "suggest", "advise", "escalate"
    ] = Field(..., description="Level of human involvement required")
    aggression: Literal["conservative", "moderate", "aggressive"] = Field(
        ..., description="How aggressively the plan responds to the threat"
    )
    threat_summary: str = Field(
        ..., description="One-paragraph summary of the threat and proposed response"
    )
    actions: list[Action] = Field(..., min_length=1, description="Ordered list of actions")
    estimated_total_duration: int = Field(
        0, description="Total estimated seconds to execute all actions"
    )

    def model_post_init(self, __context):
        if self.estimated_total_duration == 0:
            self.estimated_total_duration = sum(a.estimated_duration_seconds for a in self.actions)


class PlanSet(BaseModel):
    """
    The complete output of the Planning Agent for a single alert.
    Contains 2-3 ranked plans plus shared context.
    """
    alert_id: str
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    threat_summary: str = Field(..., description="High-level threat description")
    plans: list[ExecutionPlan] = Field(..., min_length=1, max_length=5)

    # Shared context references (for the dashboard to display)
    cve_matches: list[dict] = Field(default_factory=list)
    affected_assets: list[dict] = Field(default_factory=list)

    @property
    def best_plan(self) -> ExecutionPlan:
        """Return the highest-confidence plan."""
        return max(self.plans, key=lambda p: p.confidence)


class ApprovedAction(BaseModel):
    """
    Message published to 'approved-actions' Kafka topic when the analyst
    approves a plan (possibly with modifications).
    """
    plan_id: str = Field(..., description="Which plan was approved")
    alert_id: str
    approved_by: str = Field(..., description="Analyst username or ID")
    approval_timestamp: datetime = Field(default_factory=datetime.utcnow)
    actions: list[Action] = Field(..., description="Actions to execute (may be modified)")
    modifications: Optional[str] = Field(
        None, description="Description of any changes the analyst made"
    )
    notes: Optional[str] = Field(None, description="Analyst notes for audit trail")


class ActionResult(BaseModel):
    """
    Result of executing a single action, published to 'action-results' topic.
    The orchestrator consumes these to track progress and detect failures.
    """
    action_id: str
    alert_id: str
    plan_id: Optional[str] = Field(None, description="Plan this action belongs to")
    status: Literal["completed", "failed", "timeout", "skipped", "blocked", "dry_run"] = Field(
        ..., description="Execution outcome"
    )
    output: Optional[dict] = Field(
        None, description="Executor-specific result data"
    )
    error: Optional[str] = Field(None, description="Error message if failed")
    duration_ms: int = Field(0, description="Actual execution time in milliseconds")
    completed_at: datetime = Field(default_factory=datetime.utcnow)
    rollback_available: bool = Field(False, description="Whether rollback is possible")
